// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js";
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js";

/** Component return type for Next.js pages and layouts */
type ComponentReturn =
  | React.ReactNode
  | Promise<React.ReactNode>
  | never
  | void
  | Promise<void>;

/** Props for page components */
type PageProps<Route extends AppRoutes = AppRoutes> = {
  params: Promise<ParamMap[Route]>;
} & any;

/** Props for layout components */
type LayoutProps<Route extends LayoutRoutes = LayoutRoutes> = {
  params: Promise<ParamMap[Route]>;
  children: React.ReactNode;
} & any;

/** Shared configuration for pages and layouts */
type BaseConfig<Props> = {
  default: React.ComponentType<Props> | ((props: Props) => ComponentReturn);
  generateStaticParams?: (props: { params: Record<string, any> }) => Promise<any[]> | any[];
  generateMetadata?: (props: Props, parent: ResolvingMetadata) => Promise<any> | any;
  generateViewport?: (props: Props, parent: ResolvingViewport) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type AppPageConfig<Route extends AppRoutes = AppRoutes> = BaseConfig<PageProps<Route>>;

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = BaseConfig<LayoutProps<Route>>;

// Type validation blocks
declare module "../app/page.js" {
  const handler: AppPageConfig<"/">;
}

declare module "../app/layout.js" {
  const handler: LayoutConfig<"/">;
}
